"""add settings tables

Revision ID: 154efba30874
Revises: b44db59105db
Create Date: 2026-05-23 00:31:10.705075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '154efba30874'
down_revision: Union[str, Sequence[str], None] = 'b44db59105db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
      # Get the database connection
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Check if table already exists
    if 'setting_groups' not in inspector.get_table_names():
        op.create_table('setting_groups',
        sa.Column('id', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('NEWID()'), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_group_lookup', 'setting_groups', ['is_active', 'deleted_at'], unique=False)
        op.create_index('idx_group_name', 'setting_groups', ['name'], unique=False)

    if 'settings' not in inspector.get_table_names():    
        op.create_table('settings',
        sa.Column('id', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('NEWID()'), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('setting_group_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['setting_group_id'], ['setting_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_setting_lookup', 'settings', ['is_active', 'deleted_at'], unique=False)
        op.create_index('idx_setting_name', 'settings', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_setting_name', table_name='settings')
    op.drop_index('idx_setting_lookup', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_group_name', table_name='setting_groups')
    op.drop_index('idx_group_lookup', table_name='setting_groups')
    op.drop_table('setting_groups')
    # ### end Alembic commands ###
