"""update sharepoints table

Revision ID: 625b376815aa
Revises: c4a5b6d7e8f9
Create Date: 2026-08-09 16:57:22.627706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625b376815aa'
down_revision: Union[str, Sequence[str], None] = 'c4a5b6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_sharepoints_sync_candidates'), table_name='sharepoints', postgresql_where='(is_file AND enable_sync AND (deleted_at IS NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sharepoints_sync_candidates'), 'sharepoints', ['file_size'], unique=False, postgresql_where='(is_file AND enable_sync AND (deleted_at IS NULL))')
    op.create_index(op.f('idx_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
