"""add included_sites to department_sharepoint_links

Revision ID: 71ff7d79e5dc
Revises: 6da6ff0cf2c8
Create Date: 2026-08-09 06:50:29.980737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71ff7d79e5dc'
down_revision: Union[str, Sequence[str], None] = '6da6ff0cf2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_sharepoint_links', sa.Column('included_sites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_sharepoint_links', 'included_sites')
    # ### end Alembic commands ###
