"""fix address table

Revision ID: b44db59105db
Revises: 001add_email_verified
Create Date: 2026-05-23 00:21:51.575703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44db59105db'
down_revision: Union[str, Sequence[str], None] = '001add_email_verified'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country_code'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_country_code'), 'users', ['country_code'], unique=False)
    # ### end Alembic commands ###
