"""add included_sites to department_sharepoint_links

Revision ID: bc39d6c96509
Revises: 7c6ebd9325f1
Create Date: 2026-08-09 06:50:54.777067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc39d6c96509'
down_revision: Union[str, Sequence[str], None] = '7c6ebd9325f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
