"""Add unique constraint for tenant_id and slug

Revision ID: ce0c89af19fd
Revises: 783851a39fd7
Create Date: 2026-08-05 13:50:49.139550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0c89af19fd'
down_revision: Union[str, Sequence[str], None] = '783851a39fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_services', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('tenant_services', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('tenant_services', sa.Column('slug', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('tenant_services_service_code_key'), 'tenant_services', type_='unique')
    op.create_unique_constraint('uq_tenant_service_tenant_slug', 'tenant_services', ['tenant_id', 'slug'])
    op.create_unique_constraint(None, 'tenant_services', ['code'])
    op.drop_column('tenant_services', 'service_name')
    op.drop_column('tenant_services', 'service_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_services', sa.Column('service_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tenant_services', sa.Column('service_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_services', type_='unique')
    op.drop_constraint('uq_tenant_service_tenant_slug', 'tenant_services', type_='unique')
    op.create_unique_constraint(op.f('tenant_services_service_code_key'), 'tenant_services', ['service_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenant_services', 'slug')
    op.drop_column('tenant_services', 'code')
    op.drop_column('tenant_services', 'name')
    # ### end Alembic commands ###
