"""add : brands,categories,products

Revision ID: ee728e3da787
Revises: 154efba30874
Create Date: 2026-06-01 00:27:02.606473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'ee728e3da787'
down_revision: Union[str, Sequence[str], None] = '154efba30874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setting_groups', 'description',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('setting_groups', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('setting_groups', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('setting_groups', 'deleted_at',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_group_lookup'), table_name='setting_groups')
    op.drop_index(op.f('idx_group_name'), table_name='setting_groups')
    op.create_index(op.f('ix_setting_groups_deleted_at'), 'setting_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_setting_groups_name'), 'setting_groups', ['name'], unique=True)
    op.alter_column('settings', 'description',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('settings', 'value',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('settings', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('settings', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('settings', 'deleted_at',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_setting_lookup'), table_name='settings')
    op.drop_index(op.f('idx_setting_name'), table_name='settings')
    op.create_index(op.f('ix_settings_deleted_at'), 'settings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_settings_name'), 'settings', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_name'), table_name='settings')
    op.drop_index(op.f('ix_settings_deleted_at'), table_name='settings')
    op.create_index(op.f('idx_setting_name'), 'settings', ['name'], unique=False)
    op.create_index(op.f('idx_setting_lookup'), 'settings', ['is_active', 'deleted_at'], unique=False)
    op.alter_column('settings', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=True)
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=False)
    op.alter_column('settings', 'created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('settings', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_index(op.f('ix_setting_groups_name'), table_name='setting_groups')
    op.drop_index(op.f('ix_setting_groups_deleted_at'), table_name='setting_groups')
    op.create_index(op.f('idx_group_name'), 'setting_groups', ['name'], unique=False)
    op.create_index(op.f('idx_group_lookup'), 'setting_groups', ['is_active', 'deleted_at'], unique=False)
    op.alter_column('setting_groups', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=True)
    op.alter_column('setting_groups', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=False)
    op.alter_column('setting_groups', 'created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=False)
    op.alter_column('setting_groups', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
